### ISSUE TITLE
Add ability to change apiVersion in the url for GET and PUT

### ISSUE THREAD

**Issue by puneetsaraswat** [projectkudu/AzureResourceExplorer#159]
We need to use different apiVersions which are not the default version of the resource. Ability to change apiVersion will be very handy feature.

**Comment by bala16** [comment]
@puneetsaraswat  we pick the api version from the swagger api files from https://github.com/Azure/azure-rest-api-specs. I would like to understand your scenario better to see how we can support this. Are you looking to use a different api version because the default api version doesn't work or is incorrect? 

Also https://resources.azure.com/raw/ supports running any arbitrary get/post request.

**Comment by puneetsaraswat** [comment]
@bala16 We need this capability to try non default API versions for exercising preview api versions which may not be set to default in swagger yet.

I was not aware of https://resources.azure.com/raw/ This seems to be good enough for our purpose.
