### ISSUE TITLE
Control over API version

### ISSUE THREAD

**Issue by jtuliani** [projectkudu/AzureResourceExplorer#197]
Please can we have an option to control the API version for each call?

Very useful to explore how resource properties have changed between API versions.

**Comment by bala16** [comment]
If you are looking to specify a different api-version when making arm calls check out https://resources.azure.com/raw/

Right now the tool supports only one api version (usually the latest) to keep things simple.

**Comment by jtuliani** [comment]
Thanks @bala16, I hadn't seen that before (I couldn't find a link from the vanilla resources.azure.com site, perhaps there should be so it's more discoverable?)

Does using /raw also allow me to control HTTP request headers (required for specifying If-Match / If-None-Match etag headers)? If so, I couldn't see how.

**Comment by snobu** [comment]
I believe that raises a valid point, @bala16 how about we stick a permanent banner up top?

![image](https://user-images.githubusercontent.com/6472374/43146314-ab1097e2-8f69-11e8-94a3-6434b1d0db0d.png)

**Comment by ahmelsayed** [comment]
No you can't do headers unfortunately. You can only control the URL and body. 

That view is very incomplete. I added it because I found it useful for quick testing, but it's far from complete. For starters I don't really like the name :)

Though if you are a vscode user, I highly recommend trying https://github.com/Huachao/vscode-restclient 

Here is a quick gif of how it works 

![peek 2018-07-24 10-42](https://user-images.githubusercontent.com/645740/43156229-64c547a0-8f2e-11e8-8aad-ed41ea259e7a.gif)

**Comment by snobu** [comment]
If you're on Windows, [ARMClient](https://github.com/projectkudu/armclient) can do custom headers, as well as arbitrary API versions. Try it out.

**Comment by jtuliani** [comment]
Thanks for the suggestion, I got everything working in Postman in the end. Setting up the auth token is easy, just copy from az account get-access-token

**Comment by snobu** [comment]
Closing this one, but not before a big thank you to @ahmelsayed for mentioning the life-changing REST extension for VSCode. Makes Postman look like a savage.
