### ISSUE TITLE
Storage Account /services request fails

### ISSUE THREAD

**Issue by bvirkler** [projectkudu/AzureResourceExplorer#55]
Retrieve a storage account, i.e., `/resourceGroups/my-group/providers/Microsoft.ClassicStorage/storageAccounts/mystorage`, works fine.  Trying to drill down into the services, i.e., `/resourceGroups/my-group/providers/Microsoft.ClassicStorage/storageAccounts/mystorage/services`, spins forever.  Fiddler shows a 400 Bad Request coming back.

**Comment by ahmelsayed** [comment]
We have a UI bug in how we handle failures from ARM. Basically it only works on the first time, then we lose the observable subscription, so the UI spins forever. 
I also think the 400 may disappear if we explicitly set an `accept` header on our calls to ARM, which we don't now. I'll take a look at both issues.

**Comment by bala16** [comment]
400 is due to some of these operations not being supported for Microsoft.ClassicStorage provider.

Get-AzureRmMetricDefinition -ResourceId /subscriptions/<subId>/resourceGroups/<ResGroupName>/providers/Microsoft.ClassicStorage/storageAcounts/<StorageAccName>

returns

Body:
{
  "code": "ResourceNotSupported",
  "message": "Resource provider not supported: microsoft.classicstorage"
}

Since we don't have updated swagger for this provider, we should just remove these unsupported operations. Fixed by 872da37cf30b61ece91d29b47d62ba91f24fa253
Opened #172 to track the bug with observables.
